var hoodNames = [
  "Calhoun-Isles",
  "Bryn Mawr",
  "Calhoun Area Residents Action Group (CARAG)",
  "Cedar-Isles-Dean",
  "East Calhoun",
  "East Isles",
  "Kenwood",
  "Lowry Hill",
  "The Wedge",
  "West Calhoun",
  "Camden",
  "Cleveland",
  "Folwell",
  "Lind-Bohanon",
  "McKinley",
  "Shingle Creek",
  "Victory",
  "Webber-Camden",
  "Central",
  "Downtown East",
  "Downtown West",
  "Elliot Park",
  "Loring Park",
  "North Loop",
  "Stevens Square",
  "Longfellow",
  "Cooper",
  "Hiawatha",
  "Howe",
  "Longfellow",
  "Seward",
  "Near North",  
  "Harrison",
  "Hawthorne",
  "Jordan",
  "Sumner-Glenwood",
  "Willard-Hay",
  "Nokomis",
  "Diamond Lake",
  "Ericsson Field",
  "Hale",
  "Nokomis East",
  "Keewaydin",
  "Minnehaha",
  "Morris Park",
  "Wenonah",
  "Northrop",
  "Page",
  "Regina",
  "Northeast", 
  "Audubon Park",
  "Beltrami",
  "Bottineau",
  "Columbia Park",
  "Holland",
  "Logan Park",
  "Marshall Terrace",
  "Northeast Park",
  "Sheridan",
  "St. Anthony East",
  "St. Anthony West",
  "Waite Park",
  "Windom Park",
  "Phillips",
  "East Phillips",
  "Midtown Phillips",
  "Phillips West",
  "Ventura Village",
  "Powderhorn",
  "Bancroft",
  "Bryant",
  "Central",
  "Corcoran",
  "Lyndale",
  "Powderhorn Park",
  "Standish",
  "Whittier",
  "Southwest",
  "Armatage East",
  "Harriet",
  "Fulton",
  "Kenny",
  "Kingfield",
  "Linden Hills",
  "Lynnhurst",
  "Tangletown",
  "Windom",
  "University",  
  "Cedar-Riverside",
  "Como",
  "Marcy-Holmes",
  "Nicollet Island",
  "East Bank",
  "West Bank",
  "Prospect Park",
  "University",
  "Dinkytown",
  "Downtown",
  "Eat Street",
  "50th & France",
  "Lyn-Lake",
  "Midtown",
  "Mill District",
  "Stadium Village",
  "Uptown"
];

var cityNames = [
  "Minneapolis",
  "St. Paul",
  "St. Louis Park",
  "Bloomington",
  "Edina",
  "Golden Valley",
  "Robbinsdale",
  "Richfield",
  "Falcon Heights",
  "Lauderdale",
  "Roseville"
];

var zoomCities = [
  'Afton',
  'Andover',
  'Anoka',
  'Apple Valley',
  'Arden Hills',
  'Bayport',
  'Baytown Twp.',
  'Belle Plaine',
  'Bethel',
  'Birchwood Village',
  'Blaine',
  'Bloomington',
  'Brooklyn Center',
  'Brooklyn Park',
  'Nowthen',
  'Burnsville',
  'Cedar Lake Twp.',
  'Centerville',
  'Champlin',
  'Circle Pines',
  'Coates',
  'Columbia Heights',
  'Columbus',
  'Coon Rapids',
  'Cottage Grove',
  'Credit River Twp.',
  'Crystal',
  'Dayton',
  'Deephaven',
  'Denmark Twp.',
  'Douglas Twp.',
  'Eagan',
  'East Bethel',
  'Eden Prairie',
  'Edina',
  'Elko New Market',
  'Eureka Twp.',
  'Excelsior',
  'Falcon Heights',
  'Farmington',
  'Forest Lake',
  'Fort Snelling (unorg.)',
  'Fridley',
  'Gem Lake',
  'Golden Valley',
  'Grant',
  'Greenfield',
  'Greenvale Twp.',
  'Greenwood',
  'Ham Lake',
  'Hampton',
  'Hampton Twp.',
  'Hanover',
  'Hilltop',
  'Hopkins',
  'Hugo',
  'Independence',
  'Inver Grove Heights',
  'Jackson Twp.',
  'Lake Elmo',
  'Lakeland',
  'Lakeland Shores',
  'Lake St. Croix Beach',
  'Lakeville',
  'Landfall',
  'Lauderdale',
  'Lexington',
  'Lilydale',
  'Lino Lakes',
  'Linwood Twp.',
  'Little Canada',
  'Long Lake',
  'Loretto',
  'Louisville Twp.',
  'Mahtomedi',
  'Maple Plain',
  'Maplewood',
  'Marine on St. Croix',
  'Marshan Twp.',
  'May Twp.',
  'Medicine Lake',
  'Mendota',
  'Mendota Heights',
  'Miesville',
  'Minnetonka',
  'Minnetonka Beach',
  'Minnetrista',
  'Mound',
  'Mounds View',
  'New Brighton',
  'New Hope',
  'Newport',
  'New Prague',
  'Scandia',
  'New Trier',
  'Nininger Twp.',
  'Northfield',
  'North Oaks',
  'North St. Paul',
  'Oakdale',
  'Oak Grove',
  'Oak Park Heights',
  'Orono',
  'Osseo',
  'Pine Springs',
  'Plymouth',
  'Ramsey',
  'Randolph',
  'Randolph Twp.',
  'Ravenna Twp.',
  'Richfield',
  'Robbinsdale',
  'Rockford',
  'Rosemount',
  'Roseville',
  'St. Anthony',
  'St. Bonifacius',
  'St. Francis',
  'St. Louis Park',
  'St. Marys Point',
  'St. Paul',
  'St. Paul Park',
  'Savage',
  'Sciota Twp.',
  'Shakopee',
  'Shoreview',
  'Shorewood',
  'South St. Paul',
  'Spring Lake Park',
  'Spring Park',
  'Sunfish Lake',
  'Tonka Bay',
  'Vadnais Heights',
  'Vermillion',
  'Vermillion Twp.',
  'Waterford Twp.',
  'Wayzata',
  'West Lakeland Twp.',
  'West St. Paul',
  'White Bear Twp.',
  'White Bear Lake',
  'Woodland',
  'Woodbury',
  'Jordan',
  'Minneapolis',
  'Sand Creek Twp.',
  'St. Lawrence Twp.',
  'Willernie',
  'Empire Twp.',
  'Helena Twp.',
  'Belle Plaine Twp.',
  'Castle Rock Twp.',
  'Grey Cloud Island Twp.',
  'Blakeley Twp.',
  'New Market Twp.',
  'Medina',
  'Corcoran',
  'Maple Grove',
  'Prior Lake',
  'Chanhassen',
  'San Francisco Twp.',
  'Hamburg',
  'Dahlgren Twp.',
  'Benton Twp.',
  'Cologne',
  'Young America Twp.',
  'Carver',
  'Norwood Young America',
  'Chaska',
  'Waconia',
  'Camden Twp.',
  'Victoria',
  'New Germany',
  'Watertown',
  'Mayer',
  'Watertown Twp.',
  'Hollywood Twp.',
  'Hancock Twp.',
  'Rogers',
  'Hastings',
  'Spring Lake Twp.',
  'Stillwater',
  'Dellwood',
  'Laketown Twp.',
  'Waconia Twp.',
  'Stillwater Twp.',
  'Laketown Twp.'
]